version: "3.8"

volumes:
  fileshare_postgres_volume:
    driver: local

services:
  redis:
    image: redis:alpine
    container_name: fileshare_redis
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    container_name: fileshare_postgres
    ports:
      - 5432:5432
    volumes:
      - fileshare_postgres_volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fileshare