# Generated by Django 5.0 on 2023-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileshare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("VIDEO", "Video"),
                    ("IMAGE", "Image"),
                    ("AUDIO", "Audio"),
                    ("TEXT", "Text"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
